services:
  postgres:
    image: postgres:15
    container_name: medplum-postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

  redis:
    image: redis:7
    container_name: medplum-redis
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}

  medplum-backend:
    build:
      context: ./medplum
      dockerfile: Dockerfile.server
    container_name: medplum-server
    restart: always
    volumes:
      - ./medplum.config.json:/app/packages/server/medplum.config.json
    expose:
      - 8103
    depends_on:
      - postgres
      - redis

  medplum-frontend:
    build:
      context: ./medplum
      dockerfile: Dockerfile.frontend
    container_name: medplum-web
    restart: always
    expose:
      - "3000"
    depends_on:
      - medplum-backend

  nginx:
    image: nginx:latest
    container_name: medplum-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
    depends_on:
      - medplum-frontend
      - medplum-backend

volumes:
  postgres_data:
    driver: local