FROM node:22-alpine AS build

RUN apk add --no-cache git curl openssl

WORKDIR /app

COPY . .

RUN npm ci
RUN npm run build:fast

# Final Image
FROM node:22-alpine

RUN apk add --no-cache git curl openssl
RUN addgroup -S medplum && adduser -S medplum -G medplum

WORKDIR /app
COPY --from=build /app .
RUN chown -R medplum:medplum /app
RUN chmod -R 755 /app

WORKDIR /app/packages/app

EXPOSE 3000
USER medplum

CMD ["npx", "vite", "preview", "--port", "3000", "--host"]